export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_WEB_URL),
  title: 'Next.js',
  description: 'Generated by Next.js',
  openGraph: {
    title: 'Next.js',
    description: 'Generated by Next.js',
    url: process.env.NEXT_PUBLIC_WEB_URL,
    images: '/og.jpg',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Next.js',
    description: 'Generated by Next.js',
    images: ['/og.jpg'], // Must be an absolute URL
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
