import Head from 'next/head'
import MobileNav from '@components/MobileNav';
import { Inter } from '@next/font/google';
import cn from "classnames";
import styles from '../components/index.module.css'
import { motion, useTime, useTransform } from "framer-motion";
import { FadeIn } from '@components/FadeIn';
import { Gradient } from '@components/Gradient';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const time = useTime();
  const rotate = useTransform(time, [0, 15000], [0, 360], { clamp: false });

  return (
    <>
      <Head>
        <title>Next Background Animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black text-white min-h-screen relative overflow-hidden">
        <div className={inter.className}>

          <MobileNav />

          <section id="pattern" className="relative w-full h-full flex items-center justify-center mb-48 md:mb-24">
            <FadeIn className="z-10 mt-40 md:mt-0 md:flex justify-center md:gap-16 space-y-8 sm:space-y-12 md:space-y-0 w-full">
              <div className="w-full h-[180px] md:w-1/6 relative flex items-center justify-center">
                <div className="absolute z-10 min-w-[550px] min-h-[550px] md:min-w-[600px] md:min-h-[600px]">
                  <Image
                    alt="Turborepo"
                    src="/pack-hexagons.svg"
                    fill="true"
                    className="block"
                  />
                </div>
                <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                  <Gradient
                    small
                    width={120}
                    height={120}
                    conic
                    className="opacity-100"
                  />
                </div>
                <div className="w-[150px] h-[150px] z-10">
                  <Image
                    alt=""
                    src={`/pack-logo.svg`}
                    fill="true"
                    className="block"
                  />
                </div>
              </div>
              <div className="w-full h-[180px] md:w-1/6 flex items-center justify-center">
                <h1 className="text-6xl sm:text-8xl text-transparent font-semibold bg-clip-text bg-gradient-to-r from-yellow-500 to-sky-600">&</h1>
              </div>
              <div className="w-full h-[180px] md:w-1/6 relative flex items-center justify-center">
                <div className="absolute min-w-[550px] min-h-[550px] md:min-w-[600px] md:min-h-[600px]">
                  <Image
                    alt="Turborepo"
                    src="/pack-hexagons.svg"
                    fill="true"
                    className="block"
                  />
                </div>
                <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                  <Gradient
                    small
                    width={120}
                    height={120}
                    conic
                    className="opacity-100"
                  />
                </div>
                <div className="w-[150px] h-[150px] z-10">
                  <Image
                    alt=""
                    src={`/pack-logo.svg`}
                    fill="true"
                    className="block"
                  />
                </div>
              </div>
            </FadeIn>
            <Gradient
              width={1000}
              height={700}
              className="top-[-200px] opacity-20"
              conic
            />
            <div className="absolute top-0 z-10 w-full h-52 from-black to-transparent bg-gradient-to-b" />
          </section>

          <section className="relative h-full flex items-center">
            <div className="flex flex-col md:flex-row w-full items-center justify-center gap-16">
              <FadeIn delay={0.3}>
                <div
                  className={cn(
                    styles["counter-border"],
                    "no-underline"
                  )}
                >
                  <motion.i
                    initial="visible"
                    animate={{ opacity: 1 }}
                    variants={{
                      hidden: { opacity: 0 },
                      active: { opacity: 1 },
                    }}
                    aria-hidden="true"
                  ></motion.i>
                  <div className="p-8 rounded-lg">
                    <div className="relative flex items-center justify-center">
                      <div className="z-10 absolute w-54 h-54 inset-0 bg-gradient-to-b from-sky-700 to-green-500 mix-blend-normal opacity-[0.15] blur-[60px]" />
                      <div className="bg-black h-64 w-64">
                      </div>
                    </div>
                    <div className="flex justify-center">
                      <span className="text-2xl no-underline mt-2 font-bold text-gray-200 tracking-wide">Title</span>
                    </div>
                  </div>
                </div>
              </FadeIn>
              <div className="flex items-center justify-center text-6xl sm:text-8xl text-transparent font-semibold bg-clip-text bg-gradient-to-r from-yellow-500 to-sky-600">
                &
              </div>
              <FadeIn delay={0.5}>
                <div
                  className={cn(
                    styles["counter-border-blue"],
                    "no-underline"
                  )}
                >
                  <motion.i
                    initial="visible"
                    animate={{ opacity: 1 }}
                    variants={{
                      hidden: { opacity: 0 },
                      active: { opacity: 1 },
                    }}
                    aria-hidden="true"
                  ></motion.i>
                  <div className="p-8 rounded-lg">
                    <div className="relative flex items-center justify-center">
                      <div className="z-10 absolute w-54 h-54 inset-0 bg-gradient-to-b from-sky-700 to-green-500 mix-blend-normal opacity-[0.15] blur-[60px]" />
                      <div className="bg-black h-64 w-64">
                      </div>
                    </div>
                    <div className="flex justify-center">
                      <span className="text-2xl no-underline mt-2 font-bold text-gray-200 tracking-wide">Title</span>
                    </div>
                  </div>
                </div>
              </FadeIn>
            </div>
          </section>

          <section id="title" className="relative h-screen w-full flex items-center my-16">
            {/* <FadeIn delay={0.5}> */}

            <div className="w-full text-center">
              <h1 className="z-10 font-extrabold md:text-left text-5xl lg:text-6xl p-4 mb-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
                John
              </h1>
              <h1 className="z-10 font-extrabold md:text-center text-5xl lg:text-6xl p-4 mb-4 text-transparent bg-clip-text bg-gradient-to-b from-yellow-500 to-sky-600">
                /
              </h1>
              <h1 className="z-10 font-extrabold md:text-right text-5xl lg:text-6xl p-4 mb-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
                Doe
              </h1>
            </div>

            {/* </FadeIn> */}
            <span className="absolute bottom-0 left-0 right-0 w-full h-48 bg-gradient-to-t from-black to-transparent" />
          </section>

          <section className="relative w-full h-screen flex items-center justify-center my-16">
            <motion.div
              className="absolute inset-0"
              style={{
                rotate,
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: '50%',
                backgroundImage: 'url(/ring-small.svg)'
              }}
            />
            <div className="home_spotlight"></div>
            <div className="z-10 text-white">
              <h1 className="z-10 mx-6 font-extrabold text-4xl lg:text-5xl leading-tight text-center mb-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
                Gradient Title
              </h1>
              <h1 className="z-10 mx-6 font-extrabold text-2xl lg:text-3xl leading-tight text-center mb-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
                Sabtu, 21 Desember
              </h1>
              <h1 className="z-10 mx-6 font-extrabold text-2xl lg:text-3xl leading-tight text-center mb-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
                2022
              </h1>
            </div>
          </section>

          <section id="gridd" className="h-screen relative">
            <div className="gridd-bg"></div>
            <div className="relative z-10 flex items-center justify-center h-screen">
              GRIDD
            </div>
          </section>

          <section className="relative z-[1] h-screen w-screen ">
            <span className={cn(styles.leftLights, "opacity-100")} />
            <span className={cn(styles.rightLights, "opacity-100")} />
            <span className="absolute bottom-0 left-0 right-0 w-full h-48 bg-gradient-to-t from-black to-transparent" />
            <span className="bg-black absolute top-[10vh] left-0 right-0 w-full h-[30vh]" />
            <span class="bg-gradient-to-b from-black to-transparent absolute top-[20vh] left-0 right-0 w-full h-[550vh]"></span>
            <div className="container ![perspective:1000px]">
              <div className="absolute inset-0"
                style={{
                  transform: "rotateX(75deg)",
                }}
              >
                <div className="lines" />
              </div>
            </div>
            <div className="relative flex items-center h-screen justify-center">
              aa
            </div>
          </section>

        </div>
      </main >
    </>
  )
}
