export async function generateMetadata({ searchParams }) {
  const name = searchParams.to;
  console.log(name);
  const image = name !== undefined ? `/ogs?name=${searchParams.to}` : '/og.jpg';
  return {
    metadataBase: new URL(process.env.NEXT_PUBLIC_WEB_URL),
    title: 'Next.js',
    description: 'Generated by Next.js',
    openGraph: {
      title: 'Next.js',
      description: 'Generated by Next.js',
      url: process.env.NEXT_PUBLIC_WEB_URL,
      images: image,
    },
    twitter: {
      card: 'summary_large_image',
      title: 'Next.js',
      description: 'Generated by Next.js',
      images: [image], // Must be an absolute URL
    },
  };
}

export default function Page() {
  return <h1>Hello, Next.js!</h1>;
}
