import { recipients } from '@data/recipients';

export async function generateMetadata({ searchParams }) {
  const recipient = recipients.find((item) => item.slug == searchParams.to) || { name: 'Tamu Undangan' };
  const image = recipient.name !== 'Tamu Undangan' ? `/ogs?name=${recipient.name}` : '/og.jpg';
  return {
    metadataBase: new URL(process.env.NEXT_PUBLIC_WEB_URL),
    title: 'Next.js',
    description: 'Generated by Next.js',
    openGraph: {
      title: 'Next.js',
      description: 'Generated by Next.js',
      url: process.env.NEXT_PUBLIC_WEB_URL,
      images: image,
    },
    twitter: {
      card: 'summary_large_image',
      title: 'Next.js',
      description: 'Generated by Next.js',
      images: [image], // Must be an absolute URL
    },
  };
}

export default function Page() {
  return <h1>Hello, Next.js!</h1>;
}
